### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mrzev123** [d1sUa/DisDDos#2]
![image](https://user-images.githubusercontent.com/39166589/162565434-7b9d8c86-a2a2-4d0c-96ab-232292ff0aab.png)

**Comment by d1sUa** [comment]
how exactly did you open it?

**Comment by mrzev123** [comment]
> How exactly did you open it? it must work. check if all files is correct unpacked and just open .exe

I only did run, that's the result. Maybe your software needed some those requirements to installed. That's so hassle for us.

**Comment by d1sUa** [comment]
> Maybe your software needed some those requirements to installed

no, it doesn't
i will try to check if something is incorrect.
